spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: investors
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
